### ISSUE TITLE
Move all styled components into their own file and import where needed. Will help code readability and debugging.

### ISSUE THREAD

**Issue by ryanaolea** [FEC-Dexter-s-Laboratory/Project-Atelier#34]
https://github.com/FEC-Dexter-s-Laboratory/Project-Atelier/blob/4db0ecc5daae33026c611868b07884f09b57afe8/client/src/components/Overview/Overview.jsx#L7

**Comment by mrrobotisreal** [comment]
I feel like it's more organized when it's kept in the same file. But I will make note of this!
